# Generated by Django 4.2.19 on 2025-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productpricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('waste_category', models.CharField(max_length=100)),
                ('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='waste_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Purchased', 'Purchased')], default='Available', max_length=20)),
            ],
        ),
    ]
